# Generated by Django 4.2.10 on 2024-02-21 14:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_pointofinterest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='ratings',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
